####################################################################
####   crdviya.yml                                                                   ####
####################################################################
####################################################################
#### Author: SAS Institute Inc.                                                                                       ####
####                                                                                                                                           ####
####################################################################
####################################################################
#
# Copyright (c) 2019-2022, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: viyas.company.com
spec: 
   group: company.com
   versions:
     - name: v1
       served: true
       storage: true
       schema:
         openAPIV3Schema:
           type: object
           properties:
             spec:
               type: object
               properties:
                 company:
                   type: string
                 industry:
                   type: string
                   enum:
                   - software
                 replicas:
                   type: integer
                   minimum: 1
               required: ["company", "industry"]
           required: ["spec"]
   scope: Namespaced
   names: 
      plural: viyas
      kind: Viya
      shortNames:
      - vyc
